### ISSUE TITLE
placeholder is both fed and fetched

### ISSUE THREAD

**Issue by pfeodrippe** [Zeta36/tensorflow-tex-wavenet#1]
what does it mean?

```
python generate.py --text_out_path=output.txt --samples 2000 ./logdir/train/2016-10-02T10-45-10/model.ckpt-14999
Restoring model from ./logdir/train/2016-10-02T10-45-10/model.ckpt-14999
Sample 1967/2000
E tensorflow/core/client/tensor_c_api.cc:485] Placeholder:0 is both fed and fetched.
Traceback (most recent call last):
  File "generate.py", line 171, in <module>
    main()
  File "generate.py", line 164, in main
    out = sess.run(decode, feed_dict={samples: waveform})
  File "/Users/mac/Documents/Poli/TCC/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/Users/mac/Documents/Poli/TCC/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/mac/Documents/Poli/TCC/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/Users/mac/Documents/Poli/TCC/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Placeholder:0 is both fed and fetched.
```

**Comment by Zeta36** [comment]
@pfeodrippe, try first training your own model and then generate from it. This error maybe due to using my checkout for generating the samples.

**Comment by Zeta36** [comment]
Remember also that TensorFlow 0.10  needs to be installed before running the training script. Check your Tensorflow version.

**Comment by DenisSergeevitch** [comment]
@Zeta36 
Hi, looks like I have the same issue but with fresh trained data on tensorflow (0.10.0):

> $ python generate.py --text_out_path=krug.txt --samples 2000 ./logdir/train/2016-11-21T14-17-23/model.ckpt-3999
> Restoring model from ./logdir/train/2016-11-21T14-17-23/model.ckpt-3999
> Sample 1999/2000
> Traceback (most recent call last):
>   File "generate.py", line 171, in <module>
>     main()
>   File "generate.py", line 164, in main
>     out = sess.run(decode, feed_dict={samples: waveform})
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors.InvalidArgumentError: Placeholder:0 is both fed and fetched.

**Comment by lfelipesv** [comment]
From this post: http://stackoverflow.com/questions/39307108/placeholder-20-is-both-fed-and-fetched

I changed the following line in the file generate.py:

**decode = samples** 

I changed to:

**decode = tf.identity(samples)**

It seems ok right now... but i think is better to re evaluate the logic in the generating script
